services:
  ai-chat-bot-nuxt:
   build:
    context: .
    dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - ai-chat-bot-nuxt
    ports:
      - "80:80"
